version: '3.3'

services:

  server:
    build: .
    ports:
      - '1651:22'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 100M
