version: '3.8'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '1702:80'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 150M
    healthcheck:
      test: curl -I --fail http://localhost/ || exit 1
      interval: 60s
      timeout: 2s
      retries: 5
